/*
 * Login.java
 *
 * Modified on 2014-06-10
 */
package it.unina.db2014;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 * Finestra di dialogo per impostare i parametri di connessione al Database.
 *
 * @author Massimo
 * @author ADeLuca
 * @version %I%, 2013
 */
public class Login extends javax.swing.JDialog {

   public static final int PREMUTO_ANNULLA = 0;
   public static final int PREMUTO_LOGIN = 1;

   /**
    * Creates new form Login.
    */
   public Login(java.awt.Frame parent, boolean modal) {
      super(parent, modal);
      initComponents();
      //this.tHost.setText(Database.host);
      //this.tPorta.setText("" + Database.porta);
      //this.tServizio.setText(Database.servizio);
      //this.tSchema.setText(Database.schema);
      //this.tUser.setText(Database.user);
      //this.tPassword.setText(Database.password);
      this.tUser.requestFocus();
   }
   private int bottonePremuto;

   public int getBottonePremuto() {
      return bottonePremuto;
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bLogin = new javax.swing.JButton();
        bAnnulla = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tSchema = new javax.swing.JTextField();
        tHost = new javax.swing.JTextField();
        tServizio = new javax.swing.JTextField();
        tPorta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tUser = new javax.swing.JTextField();
        tPassword = new javax.swing.JPasswordField();
        checkSchema = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bLogin.setText("Login");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        bAnnulla.setText("Annulla");
        bAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnnullaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setText("Login");

        jLabel1.setText("Host");

        jLabel2.setText("Porta");

        jLabel3.setText("Servizio");

        jLabel7.setText("Schema");

        tSchema.setText("gruppo06");
        tSchema.setEnabled(false);

        tHost.setText("143.225.117.238");
        tHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tHostActionPerformed(evt);
            }
        });

        tServizio.setText("XE");

        tPorta.setText("1521");

        jLabel4.setText("Utente");

        jLabel5.setText("Password");

        tUser.setText("gruppo06");
        tUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tUserKeyReleased(evt);
            }
        });

        tPassword.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tPassword.setText("flockr");
        tPassword.setPreferredSize(new java.awt.Dimension(30, 20));

        checkSchema.setSelected(true);
        checkSchema.setText("come Utente");
        checkSchema.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkSchemaStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(47, 47, 47)
                        .add(jLabel6))
                    .add(layout.createSequentialGroup()
                        .add(31, 31, 31)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(jLabel1)
                            .add(jLabel3)
                            .add(jLabel7)
                            .add(jLabel4)
                            .add(jLabel5))))
                .add(1, 1, 1)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(tPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 282, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tUser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 282, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tHost, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 231, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tPorta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tServizio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(tSchema)
                        .add(18, 18, 18)
                        .add(checkSchema)))
                .addContainerGap(81, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(87, 87, 87)
                .add(bLogin)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 119, Short.MAX_VALUE)
                .add(bAnnulla)
                .add(83, 83, 83))
        );

        layout.linkSize(new java.awt.Component[] {tHost, tPassword, tPorta, tServizio, tUser}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel6)
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(tHost, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tPorta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tServizio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tSchema, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7)
                    .add(checkSchema))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tUser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 25, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bLogin)
                    .add(bAnnulla))
                .add(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnnullaActionPerformed
       bottonePremuto = PREMUTO_ANNULLA;
       dispose();
    }//GEN-LAST:event_bAnnullaActionPerformed

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
       Database.host = tHost.getText();
       try {
          Database.porta = Integer.parseInt(tPorta.getText());
       } catch (NumberFormatException e) {
          JOptionPane.showMessageDialog(this, "La porta dev'essere"
                  + " un numero", "Errore", JOptionPane.ERROR_MESSAGE);
       }
       Database.schema = tSchema.getText();
       Database.servizio = tServizio.getText();
       Database.user = tUser.getText();
       Database.password = new String(tPassword.getPassword());
       try {
          Database.setDefaultConnection(Database.nuovaConnessione());
          //new Main().setVisible(true);
          bottonePremuto = PREMUTO_LOGIN;
          dispose();
       } catch (SQLException e) {
          JOptionPane.showMessageDialog(this, "Connessione fallita (credenziali"
                  + " errate?)", "Errore", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_bLoginActionPerformed

   private void checkSchemaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkSchemaStateChanged
      if (checkSchema.isSelected())
              {
                 tSchema.setText(tUser.getText());
                 tSchema.setEnabled(false);
              }
      else
         tSchema.setEnabled(true);
   }//GEN-LAST:event_checkSchemaStateChanged

   private void tUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tUserKeyReleased
      if (checkSchema.isSelected())
         tSchema.setText(tUser.getText());
   }//GEN-LAST:event_tUserKeyReleased

    private void tHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tHostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tHostActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnnulla;
    private javax.swing.JButton bLogin;
    private javax.swing.JCheckBox checkSchema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tHost;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tPorta;
    private javax.swing.JTextField tSchema;
    private javax.swing.JTextField tServizio;
    private javax.swing.JTextField tUser;
    // End of variables declaration//GEN-END:variables
}
