/*
 * Principale.java
 *
 * Modified on 2013-06-02
 */
package it.unina.db2014;

/**
 * Frame principale.
 *
 * @author Massimo
 * @author ADeLuca
 */
public class Principale extends javax.swing.JFrame {

   /**
    * Creates new form Principale.
    */
   public Principale() {
      initComponents();
      Login l;
      l = new Login(this, true);
      l.setVisible(true);
      if (l.getBottonePremuto() == Login.PREMUTO_ANNULLA) {
         dispose();
      } else {
         setVisible(true);
      }
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        bCarateristica1 = new javax.swing.JButton();
        bCarateristica2 = new javax.swing.JButton();
        bCarateristica3 = new javax.swing.JButton();
        bCarateristica4 = new javax.swing.JButton();
        bCarateristica5 = new javax.swing.JButton();
        bCarateristica6 = new javax.swing.JButton();
        bCarateristica7 = new javax.swing.JButton();
        bCarateristica8 = new javax.swing.JButton();
        bCarateristica9 = new javax.swing.JButton();
        bCarateristica10 = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        menFile = new javax.swing.JMenu();
        miLogin = new javax.swing.JMenuItem();
        miEsci = new javax.swing.JMenuItem();
        menFunzioni = new javax.swing.JMenu();
        miMarca = new javax.swing.JMenuItem();
        miModello = new javax.swing.JMenuItem();
        miAllestimento = new javax.swing.JMenuItem();
        miCaratteristica = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Laboratorio di basi di dati");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unina/flockr-diag2.jpg"))); // NOI18N

        jToolBar2.setRollover(true);

        bCarateristica1.setText("Utente");
        bCarateristica1.setFocusable(false);
        bCarateristica1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCarateristica1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bCarateristica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCarateristica1ActionPerformed(evt);
            }
        });
        jToolBar2.add(bCarateristica1);

        bCarateristica2.setText("Album");
        bCarateristica2.setFocusable(false);
        bCarateristica2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCarateristica2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bCarateristica2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCarateristica2ActionPerformed(evt);
            }
        });
        jToolBar2.add(bCarateristica2);

        bCarateristica3.setText("Foto");
        bCarateristica3.setFocusable(false);
        bCarateristica3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCarateristica3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bCarateristica3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCarateristica3ActionPerformed(evt);
            }
        });
        jToolBar2.add(bCarateristica3);

        bCarateristica4.setText("Video");
        bCarateristica4.setFocusable(false);
        bCarateristica4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCarateristica4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bCarateristica4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCarateristica4ActionPerformed(evt);
            }
        });
        jToolBar2.add(bCarateristica4);

        bCarateristica5.setText("Gruppo");
        bCarateristica5.setFocusable(false);
        bCarateristica5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCarateristica5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bCarateristica5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCarateristica5ActionPerformed(evt);
            }
        });
        jToolBar2.add(bCarateristica5);

        bCarateristica6.setText("Discussione");
        bCarateristica6.setFocusable(false);
        bCarateristica6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCarateristica6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bCarateristica6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCarateristica6ActionPerformed(evt);
            }
        });
        jToolBar2.add(bCarateristica6);

        bCarateristica7.setText("Commento");
        bCarateristica7.setFocusable(false);
        bCarateristica7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCarateristica7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bCarateristica7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCarateristica7ActionPerformed(evt);
            }
        });
        jToolBar2.add(bCarateristica7);

        bCarateristica8.setText("Raccolta");
        bCarateristica8.setFocusable(false);
        bCarateristica8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCarateristica8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bCarateristica8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCarateristica8ActionPerformed(evt);
            }
        });
        jToolBar2.add(bCarateristica8);

        bCarateristica9.setText("Visualizza");
        bCarateristica9.setFocusable(false);
        bCarateristica9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCarateristica9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bCarateristica9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCarateristica9ActionPerformed(evt);
            }
        });
        jToolBar2.add(bCarateristica9);

        bCarateristica10.setText("Tag");
        bCarateristica10.setFocusable(false);
        bCarateristica10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCarateristica10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bCarateristica10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCarateristica10ActionPerformed(evt);
            }
        });
        jToolBar2.add(bCarateristica10);

        menFile.setText("File");

        miLogin.setText("Login");
        miLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLoginActionPerformed(evt);
            }
        });
        menFile.add(miLogin);

        miEsci.setText("Esci");
        miEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEsciActionPerformed(evt);
            }
        });
        menFile.add(miEsci);

        jMenuBar.add(menFile);

        menFunzioni.setText("Funzioni Originali");

        miMarca.setText("Marca");
        miMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMarcaActionPerformed(evt);
            }
        });
        menFunzioni.add(miMarca);

        miModello.setText("Modello");
        miModello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModelloActionPerformed(evt);
            }
        });
        menFunzioni.add(miModello);

        miAllestimento.setText("Allestimento");
        miAllestimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAllestimentoActionPerformed(evt);
            }
        });
        menFunzioni.add(miAllestimento);

        miCaratteristica.setText("Caratteristica");
        miCaratteristica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCaratteristicaActionPerformed(evt);
            }
        });
        menFunzioni.add(miCaratteristica);

        jMenuBar.add(menFunzioni);

        setJMenuBar(jMenuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jToolBar2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jToolBar2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCaratteristicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCaratteristicaActionPerformed
       caratteristica();
    }//GEN-LAST:event_miCaratteristicaActionPerformed

    private void miEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEsciActionPerformed
       dispose();
    }//GEN-LAST:event_miEsciActionPerformed

    private void miAllestimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAllestimentoActionPerformed
       allestimento();
    }//GEN-LAST:event_miAllestimentoActionPerformed

    private void miLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLoginActionPerformed
       Login l;
       l = new Login(this, true);
       l.setVisible(true);
       if (l.getBottonePremuto() == Login.PREMUTO_ANNULLA) {
          dispose();
       }
    }//GEN-LAST:event_miLoginActionPerformed

    private void miModelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModelloActionPerformed
       modello();
    }//GEN-LAST:event_miModelloActionPerformed

    private void miMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMarcaActionPerformed
       marca();
    }//GEN-LAST:event_miMarcaActionPerformed

    private void bCarateristica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCarateristica1ActionPerformed
        utente();
    }//GEN-LAST:event_bCarateristica1ActionPerformed

    private void bCarateristica2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCarateristica2ActionPerformed
        album();
    }//GEN-LAST:event_bCarateristica2ActionPerformed

    private void bCarateristica3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCarateristica3ActionPerformed
         foto();
    }//GEN-LAST:event_bCarateristica3ActionPerformed

    private void bCarateristica4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCarateristica4ActionPerformed
        video();
    }//GEN-LAST:event_bCarateristica4ActionPerformed

    private void bCarateristica5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCarateristica5ActionPerformed
        gruppo();
    }//GEN-LAST:event_bCarateristica5ActionPerformed

    private void bCarateristica6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCarateristica6ActionPerformed
        discussione();
    }//GEN-LAST:event_bCarateristica6ActionPerformed

    private void bCarateristica7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCarateristica7ActionPerformed
        commento();
    }//GEN-LAST:event_bCarateristica7ActionPerformed

    private void bCarateristica8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCarateristica8ActionPerformed
        raccolta();
    }//GEN-LAST:event_bCarateristica8ActionPerformed

    private void bCarateristica9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCarateristica9ActionPerformed
        visualizza();
    }//GEN-LAST:event_bCarateristica9ActionPerformed

    private void bCarateristica10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCarateristica10ActionPerformed
        tag();
    }//GEN-LAST:event_bCarateristica10ActionPerformed
   
   private void discussione() {
      Discussione m;
      m = new Discussione();
      m.setVisible(true);
   }
   
   private void tag() {
      Tag m;
      m = new Tag();
      m.setVisible(true);
   }
   
   private void visualizza() {
      Visualizza m;
      m = new Visualizza();
      m.setVisible(true);
   }
   
   private void raccolta() {
      Raccolta m;
      m = new Raccolta();
      m.setVisible(true);
   }
   
   private void commento() {
      Commento m;
      m = new Commento();
      m.setVisible(true);
   }
    
   private void allestimento() {
      Allestimento m;
      m = new Allestimento();
      m.setVisible(true);
   }

   private void modello() {
      Modello m;
      m = new Modello();
      m.setVisible(true);
   }

   private void marca() {
      Marca m;
      m = new Marca();
      m.setVisible(true);
   }

   private void caratteristica() {
      Caratteristica m;
      m = new Caratteristica();
      m.setVisible(true);
   }

   private void utente() {
      Utente m;
      m = new Utente();
      m.setVisible(true);
   }
  
   private void album() {
      Album m;
      m = new Album();
      m.setVisible(true);
   }
   
   private void foto() {
      Foto m;
      m = new Foto();
      m.setVisible(true);
   }
   
   private void video() {
      Video m;
      m = new Video();
      m.setVisible(true);
   }
   
      private void gruppo() {
      Gruppo m;
      m = new Gruppo();
      m.setVisible(true);
   }

   /**
    * Lancia il thread principale (event dispatching), richiamando il
    * costruttore della classe.
    * 
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      java.awt.EventQueue.invokeLater(new Runnable() {

         public void run() {
            Principale p = new Principale();
         }
      });
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCarateristica1;
    private javax.swing.JButton bCarateristica10;
    private javax.swing.JButton bCarateristica2;
    private javax.swing.JButton bCarateristica3;
    private javax.swing.JButton bCarateristica4;
    private javax.swing.JButton bCarateristica5;
    private javax.swing.JButton bCarateristica6;
    private javax.swing.JButton bCarateristica7;
    private javax.swing.JButton bCarateristica8;
    private javax.swing.JButton bCarateristica9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JMenu menFile;
    private javax.swing.JMenu menFunzioni;
    private javax.swing.JMenuItem miAllestimento;
    private javax.swing.JMenuItem miCaratteristica;
    private javax.swing.JMenuItem miEsci;
    private javax.swing.JMenuItem miLogin;
    private javax.swing.JMenuItem miMarca;
    private javax.swing.JMenuItem miModello;
    // End of variables declaration//GEN-END:variables
}
